{{ if .Values.variables.own.secret}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: externalsecret-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    labels:
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        app: {{ .Release.Name }}
{{ if .Values.global.labels}}
{{- toYaml .Values.global.labels | indent 8 }}
{{ end }}
{{ if .Values.global.annotations}}
    annotations:
{{ toYaml .Values.global.annotations | indent 8 }}
{{ end }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: secretstore-{{ .Release.Namespace }}

  target:
    name: secret-{{ .Release.Name }}
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
{{- range $key, $secret := index .Values.variables.own.secret }}
  - secretKey: {{ $secret.name | lower | replace "_" "." }}
    remoteRef:
      key: {{ $secret.location }}
{{- end }}
{{- end }}
#New external secrets by secret store / cluster secret store
{{ $object := . -}}
{{ if $object.Values.variables.own.secrets}}
{{- range $key, $secret := index $object.Values.variables.own.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: externalsecret-{{ $object.Release.Name }}-{{ $secret.secretstore }}
    namespace: {{ $object.Release.Namespace }}
    labels:
        chart: {{ $object.Chart.Name }}
        release: {{ $object.Release.Name }}
        app: {{ $object.Release.Name }}
{{ if $object.Values.global.labels}}
{{- toYaml $object.Values.global.labels | indent 8 }}
{{ end }}
{{ if $object.Values.global.annotations}}
    annotations:
{{ toYaml $object.Values.global.annotations | indent 8 }}
{{ end }}
spec:
  refreshInterval: {{  $secret.refreshInterval | default "24h" }}
  secretStoreRef:
    kind: {{ $secret.kind | default "SecretStore" }}
    name: {{ $secret.secretstore }}

  target:
    name: secret-{{ $object.Release.Name }}-{{ $secret.secretstore }}
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
{{- range $key, $secretref := index $secret.refs }}
  - secretKey: {{ $secretref.name | lower | replace "_" "." }}
    remoteRef:
      {{ if eq "azure" $secret.provider}}
        key: {{ $secretref.location }}
      {{ end }}
      {{ if eq "aws" $secret.provider }}
        key: {{ $secretref.location }}
        property: {{ $secretref.property }}
      {{ end }}      
{{- end }}
{{- end }}
{{- end }}
