apiVersion: v1
kind: Service
metadata:
    name: service-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    labels:
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        app: {{ .Release.Name }}
{{ if .Values.global.labels}}
{{- toYaml .Values.global.labels | indent 8 }}
{{ end }}
{{ if .Values.global.annotations}}
    annotations:
{{ toYaml .Values.global.annotations | indent 8 }}
{{ end }}
spec:
    ports:
    {{- range $key, $value := .Values.container.port }}
        - name: http-{{ $.Release.Name }}
          port: {{ $value.servicePort}}
          targetPort: {{ $value.name }}
          protocol: {{ $value.protocol }}
    {{- end }}
    {{ if .Values.service }}
    {{- range $key, $value := .Values.service.ports }}
        - name: {{ $value.name }}
          port: {{ $value.servicePort}}
          targetPort: {{ $value.name }}
          protocol: {{ $value.protocol }}
    {{- end }}
    {{- end }}
    selector:
        app: {{ .Release.Name }}
{{ if not .Values.canary.enabled }}
        version: {{ .Values.global.version }}
{{ end }}
